#!/system/bin/sh
set -eu

HOME_DIR="files/home"
SHORTCUTS_DIR="$HOME_DIR/.shortcuts"
BACKUP_DIR="$HOME_DIR/.run/shortcuts_backup_$(date +%Y%m%d_%H%M%S)"
STAGING_DIR="/sdcard/Download/codex_termux_widgets"

mkdir -p "$BACKUP_DIR"

cp -f "$SHORTCUTS_DIR/1_CORTAR_TEASERS.sh" "$BACKUP_DIR/1_CORTAR_TEASERS.sh"
cp -f "$SHORTCUTS_DIR/2_SUBIR_CRUDOS_YT.sh" "$BACKUP_DIR/2_SUBIR_CRUDOS_YT.sh"
cp -f "$SHORTCUTS_DIR/3_SUBIR_TEASERS_YT.sh" "$BACKUP_DIR/3_SUBIR_TEASERS_YT.sh"

cp -f "$STAGING_DIR/1_CORTAR_TEASERS.sh" "$SHORTCUTS_DIR/1_CORTAR_TEASERS.sh"
cp -f "$STAGING_DIR/2_SUBIR_CRUDOS_YT.sh" "$SHORTCUTS_DIR/2_SUBIR_CRUDOS_YT.sh"
cp -f "$STAGING_DIR/3_SUBIR_TEASERS_YT.sh" "$SHORTCUTS_DIR/3_SUBIR_TEASERS_YT.sh"
cp -f "$STAGING_DIR/4_NOTE9_WIFI_SETUP.sh" "$SHORTCUTS_DIR/4_NOTE9_WIFI_SETUP.sh"
cp -f "$STAGING_DIR/5_NOTE9_DEX_LAUNCH.sh" "$SHORTCUTS_DIR/5_NOTE9_DEX_LAUNCH.sh"
cp -f "$STAGING_DIR/cortar teasers .sh" "$SHORTCUTS_DIR/cortar teasers .sh"

chmod 755 \
  "$SHORTCUTS_DIR/1_CORTAR_TEASERS.sh" \
  "$SHORTCUTS_DIR/2_SUBIR_CRUDOS_YT.sh" \
  "$SHORTCUTS_DIR/3_SUBIR_TEASERS_YT.sh" \
  "$SHORTCUTS_DIR/4_NOTE9_WIFI_SETUP.sh" \
  "$SHORTCUTS_DIR/5_NOTE9_DEX_LAUNCH.sh" \
  "$SHORTCUTS_DIR/cortar teasers .sh"

printf 'backup=%s\n' "$BACKUP_DIR"
ls -lb "$SHORTCUTS_DIR"
