#!/system/bin/sh
set -eu

HOME_DIR="files/home"
SHORTCUTS_DIR="$HOME_DIR/.shortcuts"
BACKUP_DIR="$HOME_DIR/.run/shortcuts_backup_$(date +%Y%m%d_%H%M%S)"
STAGING_DIR="/sdcard/Download/codex_termux_widgets"

mkdir -p "$BACKUP_DIR"

# Backup existing
cp -f "$SHORTCUTS_DIR/1_CORTAR_TEASERS.sh" "$BACKUP_DIR/1_CORTAR_TEASERS.sh" 2>/dev/null || true
cp -f "$SHORTCUTS_DIR/2_SUBIR_CRUDOS_YT.sh" "$BACKUP_DIR/2_SUBIR_CRUDOS_YT.sh" 2>/dev/null || true
cp -f "$SHORTCUTS_DIR/3_SUBIR_TEASERS_YT.sh" "$BACKUP_DIR/3_SUBIR_TEASERS_YT.sh" 2>/dev/null || true
cp -f "$SHORTCUTS_DIR/4_VIGIA_FACEBOOK.sh" "$BACKUP_DIR/4_VIGIA_FACEBOOK.sh" 2>/dev/null || true
cp -f "$SHORTCUTS_DIR/0_PIPELINE_COMPLETO.sh" "$BACKUP_DIR/0_PIPELINE_COMPLETO.sh" 2>/dev/null || true
cp -f "$SHORTCUTS_DIR/0_RENOVAR_REPO.sh" "$BACKUP_DIR/0_RENOVAR_REPO.sh" 2>/dev/null || true
cp -f "$SHORTCUTS_DIR/0_RENOVAR_TOKEN_YT.sh" "$BACKUP_DIR/0_RENOVAR_TOKEN_YT.sh" 2>/dev/null || true
cp -f "$SHORTCUTS_DIR/6_SUBIR_TIKTOK720.sh" "$BACKUP_DIR/6_SUBIR_TIKTOK720.sh" 2>/dev/null || true
cp -f "$SHORTCUTS_DIR/6_SUBIR_TIKTOK_SHIRABYOSHI.sh" "$BACKUP_DIR/6_SUBIR_TIKTOK_SHIRABYOSHI.sh" 2>/dev/null || true
cp -f "$SHORTCUTS_DIR/6_SUBIR_TIKTOK_SHIRABYOSHI_180.sh" "$BACKUP_DIR/6_SUBIR_TIKTOK_SHIRABYOSHI_180.sh" 2>/dev/null || true
cp -f "$SHORTCUTS_DIR/6_SUBIR_TIKTOK_GHAWAZEE.sh" "$BACKUP_DIR/6_SUBIR_TIKTOK_GHAWAZEE.sh" 2>/dev/null || true
cp -f "$SHORTCUTS_DIR/6_SUBIR_TIKTOK_GHAWAZEE_180.sh" "$BACKUP_DIR/6_SUBIR_TIKTOK_GHAWAZEE_180.sh" 2>/dev/null || true
cp -f "$SHORTCUTS_DIR/PARAR_TIKTOK.sh" "$BACKUP_DIR/PARAR_TIKTOK.sh" 2>/dev/null || true
cp -f "$SHORTCUTS_DIR/WATCHDOG_TIKTOK.sh" "$BACKUP_DIR/WATCHDOG_TIKTOK.sh" 2>/dev/null || true

# Copy new widgets
cp -f "$STAGING_DIR/1_CORTAR_TEASERS.sh" "$SHORTCUTS_DIR/1_CORTAR_TEASERS.sh"
cp -f "$STAGING_DIR/2_SUBIR_CRUDOS_YT.sh" "$SHORTCUTS_DIR/2_SUBIR_CRUDOS_YT.sh"
cp -f "$STAGING_DIR/3_SUBIR_TEASERS_YT.sh" "$SHORTCUTS_DIR/3_SUBIR_TEASERS_YT.sh"
cp -f "$STAGING_DIR/4_VIGIA_FACEBOOK.sh" "$SHORTCUTS_DIR/4_VIGIA_FACEBOOK.sh"
cp -f "$STAGING_DIR/6_ABRIR_SHORTCUTS.sh" "$SHORTCUTS_DIR/6_ABRIR_SHORTCUTS.sh"
cp -f "$STAGING_DIR/7_DEBIAN_MATE_LOCAL.sh" "$SHORTCUTS_DIR/7_DEBIAN_MATE_LOCAL.sh"
cp -f "$STAGING_DIR/8_DEBIAN_XFCE_LOCAL.sh" "$SHORTCUTS_DIR/8_DEBIAN_XFCE_LOCAL.sh"
cp -f "$STAGING_DIR/0_PIPELINE_COMPLETO.sh" "$SHORTCUTS_DIR/0_PIPELINE_COMPLETO.sh"
cp -f "$STAGING_DIR/0_RENOVAR_REPO.sh" "$SHORTCUTS_DIR/0_RENOVAR_REPO.sh"
cp -f "$STAGING_DIR/0_RENOVAR_TOKEN_YT.sh" "$SHORTCUTS_DIR/0_RENOVAR_TOKEN_YT.sh"
cp -f "$STAGING_DIR/Arrancar_SSH.sh" "$SHORTCUTS_DIR/Arrancar_SSH.sh"
cp -f "$STAGING_DIR/Monitor_Logs.sh" "$SHORTCUTS_DIR/Monitor_Logs.sh"
cp -f "$STAGING_DIR/Monitorear_Temperaturas.sh" "$SHORTCUTS_DIR/Monitorear_Temperaturas.sh"
cp -f "$STAGING_DIR/LIMPIAR_LOCKS.sh" "$SHORTCUTS_DIR/LIMPIAR_LOCKS.sh"
cp -f "$STAGING_DIR/RECORTAR_TODO.sh" "$SHORTCUTS_DIR/RECORTAR_TODO.sh"
cp -f "$STAGING_DIR/vigia_meta.sh" "$SHORTCUTS_DIR/vigia_meta.sh"
cp -f "$STAGING_DIR/auto_accept_mtp.sh" "$SHORTCUTS_DIR/auto_accept_mtp.sh"
cp -f "$STAGING_DIR/cortar teasers .sh" "$SHORTCUTS_DIR/cortar teasers .sh"
# TikTok base 720 se conserva y se actualiza; no se borra.
cp -f "$STAGING_DIR/6_SUBIR_TIKTOK720.sh" "$SHORTCUTS_DIR/6_SUBIR_TIKTOK720.sh"
# Cuenta Shirabyoshi TikTok (vivo-tiktok branch)
cp -f "$STAGING_DIR/6_SUBIR_TIKTOK_SHIRABYOSHI.sh" "$SHORTCUTS_DIR/6_SUBIR_TIKTOK_SHIRABYOSHI.sh"
# Clon rapido Shirabyoshi: publica cada 3 minutos (180s)
cp -f "$STAGING_DIR/6_SUBIR_TIKTOK_SHIRABYOSHI_180.sh" "$SHORTCUTS_DIR/6_SUBIR_TIKTOK_SHIRABYOSHI_180.sh"
# Cuenta Ghawazee TikTok — entrada: completados_shirabyoshi (720s y 3 min)
cp -f "$STAGING_DIR/6_SUBIR_TIKTOK_GHAWAZEE.sh" "$SHORTCUTS_DIR/6_SUBIR_TIKTOK_GHAWAZEE.sh"
cp -f "$STAGING_DIR/6_SUBIR_TIKTOK_GHAWAZEE_180.sh" "$SHORTCUTS_DIR/6_SUBIR_TIKTOK_GHAWAZEE_180.sh"
cp -f "$STAGING_DIR/PARAR_TIKTOK.sh" "$SHORTCUTS_DIR/PARAR_TIKTOK.sh"
cp -f "$STAGING_DIR/WATCHDOG_TIKTOK.sh" "$SHORTCUTS_DIR/WATCHDOG_TIKTOK.sh"

chmod 755 \
  "$SHORTCUTS_DIR/1_CORTAR_TEASERS.sh" \
  "$SHORTCUTS_DIR/2_SUBIR_CRUDOS_YT.sh" \
  "$SHORTCUTS_DIR/3_SUBIR_TEASERS_YT.sh" \
  "$SHORTCUTS_DIR/4_VIGIA_FACEBOOK.sh" \
  "$SHORTCUTS_DIR/6_ABRIR_SHORTCUTS.sh" \
  "$SHORTCUTS_DIR/7_DEBIAN_MATE_LOCAL.sh" \
  "$SHORTCUTS_DIR/8_DEBIAN_XFCE_LOCAL.sh" \
  "$SHORTCUTS_DIR/0_PIPELINE_COMPLETO.sh" \
  "$SHORTCUTS_DIR/0_RENOVAR_REPO.sh" \
  "$SHORTCUTS_DIR/0_RENOVAR_TOKEN_YT.sh" \
  "$SHORTCUTS_DIR/Arrancar_SSH.sh" \
  "$SHORTCUTS_DIR/Monitor_Logs.sh" \
  "$SHORTCUTS_DIR/Monitorear_Temperaturas.sh" \
  "$SHORTCUTS_DIR/LIMPIAR_LOCKS.sh" \
  "$SHORTCUTS_DIR/RECORTAR_TODO.sh" \
  "$SHORTCUTS_DIR/vigia_meta.sh" \
  "$SHORTCUTS_DIR/auto_accept_mtp.sh" \
  "$SHORTCUTS_DIR/cortar teasers .sh" \
  "$SHORTCUTS_DIR/6_SUBIR_TIKTOK720.sh" \
  "$SHORTCUTS_DIR/6_SUBIR_TIKTOK_SHIRABYOSHI.sh" \
  "$SHORTCUTS_DIR/6_SUBIR_TIKTOK_SHIRABYOSHI_180.sh" \
  "$SHORTCUTS_DIR/6_SUBIR_TIKTOK_GHAWAZEE.sh" \
  "$SHORTCUTS_DIR/6_SUBIR_TIKTOK_GHAWAZEE_180.sh" \
  "$SHORTCUTS_DIR/PARAR_TIKTOK.sh" \
  "$SHORTCUTS_DIR/WATCHDOG_TIKTOK.sh"

printf 'backup=%s\n' "$BACKUP_DIR"
ls -lb "$SHORTCUTS_DIR"
